package:
 name: match
 version: {{environ.get('BUILD_VERSION', "unpackaged" ) }}

build:
 number: {{ environ.get('BUILD_NUMBER', 0 ) }}


source:
 path: ../match

requirements:
 build:

 run:

about:
 license: "GPL 2"

